---
.travis.yml:
  secure: "2svx8tf0qCcHeWUq7i42ugTAZao0EBA6lIzhN2kP5AfmvTEcj9dglnc46S5+HSukqbk5TCRHyNhCDpOVUFMg6xx+YyrLrVd6wvv0X52iFuegLNkvW4/yOH0D+w7tcrNPuBKXaZc7qzbOBQyXkekQ8Tst4nvyTV2g6EZd/QN3RZM="
